version: "3.9"
name: "workspace"
services:
  frontend:
    container_name: frontend
    restart: on-failure
    depends_on:
      - backend
    build:
      context: ./frontend
      target: ${DOCKER_ENV:-dev}
    image: workspace_frontend_${DOCKER_ENV:-dev}
    ports:
      - "${FRONTEND_PORT:-80}:3000"
    volumes:
      - ./frontend:/app
    secrets:
      - backend-password
  worker:
    container_name: worker
    restart: on-failure
    depends_on:
      - database
    build:
      context: ./worker
      target: ${DOCKER_ENV:-dev}
    image: workspace_worker_${DOCKER_ENV:-dev}
    volumes:
      - ./worker:/app
    secrets:
      - database-password
      - cj-private-key
      - cj-config
      - pushover-config
  backend:
    container_name: backend
    restart: on-failure
    depends_on:
      - database
    build:
      context: ./backend
      target: ${DOCKER_ENV:-dev}
    image: workspace_backend_${DOCKER_ENV:-dev}
    ports:
      - "${BACKEND_PORT:-3001}:3001"
    volumes:
      - ./backend:/app
    secrets:
      - database-password
      - backend-password
      - smtp-config
  database:
    container_name: database
    restart: on-failure
    build:
      context: ./database
    image: workspace_database_${DOCKER_ENV:-dev}
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/database-password
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    volumes:
      - ./database/initdb:/docker-entrypoint-initdb.d
      - volume_${DOCKER_ENV:-dev}:/var/lib/postgresql/data
    secrets:
      - database-password
volumes:
  volume_dev:
  volume_prod:
secrets:
  database-password:
    file: ./database-password.txt
  backend-password:
    file: ./backend-password.txt
  cj-private-key:
    file: ./cj-private-key.txt
  cj-config:
    file: ./cj-config.txt
  smtp-config:
    file: ./smtp-config.txt
  pushover-config:
    file: ./pushover-config.txt
