version: "3.9"
name: "workspace"
services:
  frontend:
    container_name: ${COMPOSE_PROJECT_NAME:-workspace}_frontend
    restart: on-failure
    depends_on:
      - backend
    build:
      context: ./frontend
      target: ${DOCKER_ENV:-dev}
    image: ${COMPOSE_PROJECT_NAME:-workspace}_frontend
    ports:
      - "${COMPOSE_FRONTEND_PORT:-3000}:3000"
    volumes:
      - ./frontend:/app
    secrets:
      - backend-password
  worker:
    container_name: ${COMPOSE_PROJECT_NAME:-workspace}_worker
    restart: on-failure
    depends_on:
      - database
    build:
      context: ./worker
      target: ${DOCKER_ENV:-dev}
    image: ${COMPOSE_PROJECT_NAME:-workspace}_worker
    volumes:
      - ./worker:/app
    secrets:
      - database-password
      - cj-private-key
      - cj-config
      - pushover-config
  backend:
    container_name: ${COMPOSE_PROJECT_NAME:-workspace}_backend
    restart: on-failure
    depends_on:
      - database
    build:
      context: ./backend
      target: ${DOCKER_ENV:-dev}
    image: ${COMPOSE_PROJECT_NAME:-workspace}_backend
    ports:
      - "${COMPOSE_BACKEND_PORT:-3001}:3001"
    volumes:
      - ./backend:/app
    secrets:
      - database-password
      - backend-password
      - smtp-config
  database:
    container_name: ${COMPOSE_PROJECT_NAME:-workspace}_database
    restart: on-failure
    build:
      context: ./database
    image: ${COMPOSE_PROJECT_NAME:-workspace}_database
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/database-password
    ports:
      - "${COMPOSE_DATABASE_PORT:-5432}:5432"
    volumes:
      - ./database/initdb:/docker-entrypoint-initdb.d
      - volume:/var/lib/postgresql/data
    secrets:
      - database-password
volumes:
  volume:
secrets:
  database-password:
    file: ./database-password.txt
  backend-password:
    file: ./backend-password.txt
  cj-private-key:
    file: ./cj-private-key.txt
  cj-config:
    file: ./cj-config.txt
  smtp-config:
    file: ./smtp-config.txt
  pushover-config:
    file: ./pushover-config.txt
