name: Deploy
on:
  push:
    branches: [main]
jobs:
  deploy_prod:
    name: Deploy to production
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/prod.key
          chmod 600 ~/.ssh/prod.key
          cat >>~/.ssh/config <<END
          Host production
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/prod.key
            StrictHostKeyChecking no
          END
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Stop docker containers
        run: ssh production "cd $SSH_DIR && docker compose down"
        env:
          SSH_DIR: ${{ secrets.SSH_BASE_DIR }}
      - name: Fetch the code source
        run: ssh production "cd $SSH_DIR && git fetch && git reset --hard origin/main"
        env:
          SSH_DIR: ${{ secrets.SSH_BASE_DIR }}
      - name: Build docker images
        run: ssh production "cd $SSH_DIR && docker compose build"
        env:
          SSH_DIR: ${{ secrets.SSH_BASE_DIR }}
      - name: Start docker containers
        run: ssh production "cd $SSH_DIR && docker compose up -d"
        env:
          SSH_DIR: ${{ secrets.SSH_BASE_DIR }}
